In [1]:
import sqlite3

import pandas as pd
from bertopic import BERTopic

conn = sqlite3.connect("db/axiom.db")  # Creates or opens the database file
cursor = conn.cursor()

cursor.execute('''
    SELECT speech, summary
    FROM speeches s
    ORDER BY date
''')

data = cursor.fetchall()
conn.close()

print(len(data))

/home/tytan216/volume/tzeyoung/Policy_RLHF/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

8975

In [2]:
speeches = []
summary = []
for entry in data:
    speeches.append(entry[0])
    summary.append(entry[1])

base = BERTopic()
base_topics, base_probs = base.fit_transform(summary[0:7000])

new = BERTopic()
new_topics, new_probs = new.fit_transform(summary[7000:8975])

merged_model = BERTopic.merge_models([base, new])

In [3]:
df = base.get_topic_info()
df.columns.tolist()

base_topics

[-1,
 -1,
 0,
 -1,
 -1,
 0,
 -1,
 55,
 83,
 68,
 55,
 92,
 24,
 -1,
 73,
 62,
 -1,
 -1,
 -1,
 55,
 45,
 -1,
 12,
 24,
 20,
 67,
 59,
 -1,
 -1,
 -1,
 -1,
 80,
 34,
 73,
 21,
 66,
 129,
 26,
 61,
 39,
 85,
 88,
 42,
 90,
 -1,
 38,
 1,
 50,
 39,
 1,
 100,
 66,
 56,
 -1,
 62,
 -1,
 48,
 4,
 -1,
 12,
 121,
 -1,
 -1,
 38,
 50,
 112,
 41,
 -1,
 1,
 -1,
 79,
 -1,
 4,
 -1,
 8,
 31,
 9,
 -1,
 -1,
 34,
 3,
 -1,
 122,
 3,
 3,
 3,
 63,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 34,
 7,
 34,
 12,
 -1,
 20,
 9,
 57,
 -1,
 -1,
 7,
 -1,
 19,
 24,
 131,
 51,
 -1,
 54,
 -1,
 -1,
 50,
 131,
 5,
 146,
 -1,
 92,
 24,
 -1,
 3,
 54,
 2,
 3,
 25,
 42,
 0,
 86,
 131,
 21,
 5,
 1,
 61,
 51,
 131,
 -1,
 16,
 52,
 124,
 73,
 61,
 31,
 -1,
 99,
 96,
 -1,
 0,
 20,
 9,
 -1,
 12,
 22,
 8,
 -1,
 0,
 -1,
 37,
 78,
 1,
 1,
 101,
 -1,
 1,
 -1,
 51,
 -1,
 8,
 51,
 5,
 8,
 8,
 8,
 98,
 147,
 8,
 -1,
 8,
 -1,
 8,
 8,
 8,
 43,
 43,
 96,
 96,
 96,
 96,
 -1,
 24,
 60,
 45,
 45,
 45,
 9,
 123,
 32,
 110,
 10,
 -1,
 55,
 45,
 109,
 3,
 0,
 -1,
 37,
 99,
 7,
 55,
 46,
 -1,
 26,
 7,
 -1,
 2,
 -1,
 9,
 -1,
 84,
 96,
 27,
 -1,
 -1,
 72,
 61,
 -1,
 0,
 51,
 -1,
 49,
 106,
 -1,
 45,
 0,
 116,
 -1,
 2,
 78,
 30,
 37,
 23,
 -1,
 -1,
 61,
 30,
 30,
 30,
 26,
 8,
 2,
 2,
 109,
 60,
 12,
 88,
 -1,
 -1,
 74,
 30,
 30,
 124,
 30,
 30,
 30,
 2,
 128,
 74,
 74,
 111,
 30,
 88,
 91,
 0,
 56,
 30,
 100,
 11,
 -1,
 -1,
 -1,
 111,
 30,
 30,
 -1,
 28,
 57,
 74,
 0,
 28,
 19,
 -1,
 -1,
 -1,
 -1,
 1,
 111,
 -1,
 17,
 37,
 -1,
 -1,
 130,
 -1,
 118,
 124,
 35,
 -1,
 4,
 111,
 5,
 -1,
 36,
 35,
 39,
 130,
 100,
 34,
 108,
 -1,
 67,
 93,
 34,
 -1,
 54,
 -1,
 30,
 76,
 36,
 139,
 27,
 9,
 9,
 -1,
 1,
 25,
 139,
 12,
 1,
 1,
 9,
 51,
 25,
 1,
 1,
 -1,
 67,
 63,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 2,
 -1,
 60,
 -1,
 120,
 -1,
 66,
 -1,
 -1,
 134,
 10,
 48,
 17,
 48,
 44,
 -1,
 2,
 93,
 67,
 32,
 46,
 2,
 -1,
 -1,
 2,
 -1,
 2,
 2,
 2,
 -1,
 5,
 63,
 8,
 35,
 35,
 140,
 127,
 47,
 75,
 -1,
 12,
 12,
 35,
 -1,
 12,
 4,
 35,
 35,
 140,
 35,
 -1,
 -1,
 -1,
 140,
 80,
 -1,
 -1,
 127,
 67,
 -1,
 -1,
 89,
 40,
 -1,
 27,
 13,
 112,
 117,
 40,
 13,
 -1,
 11,
 -1,
 3,
 13,
 27,
 117,
 117,
 117,
 -1,
 17,
 107,
 89,
 18,
 -1,
 109,
 37,
 42,
 89,
 89,
 107,
 138,
 89,
 21,
 40,
 78,
 -1,
 112,
 -1,
 7,
 109,
 67,
 -1,
 37,
 17,
 86,
 17,
 -1,
 16,
 19,
 26,
 32,
 16,
 37,
 -1,
 29,
 42,
 26,
 139,
 30,
 72,
 37,
 -1,
 19,
 -1,
 -1,
 -1,
 22,
 64,
 -1,
 64,
 37,
 -1,
 22,
 61,
 85,
 61,
 61,
 -1,
 -1,
 22,
 58,
 93,
 67,
 -1,
 32,
 65,
 23,
 -1,
 32,
 21,
 27,
 21,
 9,
 27,
 9,
 -1,
 -1,
 9,
 21,
 -1,
 9,
 21,
 -1,
 21,
 51,
 65,
 32,
 32,
 32,
 17,
 4,
 4,
 8,
 44,
 4,
 69,
 52,
 8,
 4,
 15,
 -1,
 -1,
 -1,
 -1,
 52,
 4,
 123,
 63,
 63,
 4,
 66,
 63,
 46,
 -1,
 46,
 65,
 46,
 40,
 -1,
 17,
 7,
 -1,
 125,
 -1,
 27,
 -1,
 -1,
 -1,
 -1,
 -1,
 20,
 -1,
 33,
 -1,
 68,
 -1,
 23,
 -1,
 -1,
 21,
 23,
 23,
 2,
 -1,
 12,
 -1,
 41,
 122,
 31,
 8,
 -1,
 44,
 9,
 31,
 -1,
 111,
 -1,
 31,
 135,
 102,
 -1,
 3,
 5,
 111,
 -1,
 54,
 50,
 101,
 12,
 -1,
 9,
 22,
 0,
 -1,
 47,
 -1,
 45,
 98,
 0,
 -1,
 -1,
 -1,
 0,
 13,
 38,
 20,
 22,
 0,
 55,
 -1,
 28,
 81,
 9,
 69,
 9,
 10,
 -1,
 46,
 104,
 90,
 46,
 -1,
 -1,
 115,
 -1,
 -1,
 -1,
 9,
 3,
 111,
 87,
 -1,
 131,
 111,
 28,
 -1,
 131,
 -1,
 -1,
 38,
 45,
 49,
 6,
 39,
 87,
 136,
 23,
 38,
 64,
 31,
 -1,
 -1,
 60,
 8,
 -1,
 16,
 -1,
 3,
 58,
 1,
 -1,
 18,
 99,
 3,
 58,
 46,
 -1,
 3,
 99,
 110,
 -1,
 -1,
 0,
 -1,
 38,
 11,
 -1,
 -1,
 21,
 -1,
 54,
 42,
 59,
 -1,
 87,
 -1,
 92,
 -1,
 -1,
 70,
 16,
 127,
 -1,
 73,
 103,
 -1,
 -1,
 7,
 76,
 2,
 -1,
 -1,
 19,
 79,
 3,
 3,
 4,
 -1,
 -1,
 -1,
 3,
 0,
 63,
 -1,
 70,
 129,
 19,
 73,
 38,
 -1,
 2,
 -1,
 45,
 131,
 38,
 58,
 34,
 -1,
 118,
 73,
 -1,
 -1,
 -1,
 26,
 -1,
 140,
 72,
 9,
 120,
 -1,
 34,
 19,
 103,
 14,
 5,
 69,
 -1,
 44,
 10,
 21,
 -1,
 20,
 26,
 3,
 12,
 19,
 18,
 -1,
 -1,
 -1,
 -1,
 19,
 61,
 47,
 38,
 31,
 7,
 -1,
 3,
 -1,
 -1,
 23,
 54,
 36,
 36,
 0,
 20,
 88,
 -1,
 125,
 123,
 43,
 55,
 64,
 114,
 4,
 6,
 0,
 -1,
 121,
 -1,
 20,
 88,
 1,
 -1,
 23,
 13,
 2,
 -1,
 -1,
 25,
 15,
 1,
 57,
 -1,
 19,
 65,
 84,
 -1,
 -1,
 9,
 8,
 48,
 57,
 -1,
 -1,
 11,
 -1,
 -1,
 -1,
 71,
 9,
 3,
 71,
 -1,
 3,
 110,
 110,
 1,
 42,
 -1,
 64,
 24,
 41,
 -1,
 22,
 78,
 -1,
 -1,
 16,
 -1,
 119,
 1,
 -1,
 34,
 127,
 118,
 48,
 -1,
 137,
 107,
 64,
 -1,
 -1,
 -1,
 -1,
 64,
 64,
 42,
 75,
 -1,
 -1,
 2,
 8,
 64,
 7,
 -1,
 54,
 -1,
 22,
 0,
 22,
 -1,
 114,
 -1,
 73,
 45,
 -1,
 30,
 49,
 -1,
 118,
 27,
 -1,
 71,
 -1,
 30,
 140,
 92,
 30,
 35,
 104,
 22,
 -1,
 8,
 -1,
 15,
 -1,
 30,
 -1,
 30,
 3,
 1,
 -1,
 12,
 5,
 8,
 -1,
 59,
 -1,
 -1,
 -1,
 -1,
 38,
 51,
 48,
 8,
 16,
 -1,
 108,
 124,
 -1,
 9,
 108,
 26,
 51,
 22,
 -1,
 95,
 26,
 22,
 -1,
 144,
 109,
 -1,
 6,
 7,
 111,
 4,
 26,
 22,
 11,
 132,
 83,
 83,
 64,
 -1,
 13,
 40,
 3,
 2,
 19,
 2,
 76,
 -1,
 -1,
 25,
 -1,
 2,
 10,
 -1,
 -1,
 -1,
 132,
 1,
 19,
 7,
 17,
 -1,
 21,
 -1,
 13,
 -1,
 130,
 -1,
 -1,
 -1,
 1,
 143,
 -1,
 130,
 -1,
 17,
 13,
 ...]

In [4]:
new.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,547,-1_the_and_of_to,"[the, and, of, to, for, in, with, that, on, by]",[Ms Rahayu Mahzam outlined the Ministry's effo...
1,0,202,0_transport_bus_the_lta,"[transport, bus, the, lta, to, road, and, safe...",[Dr Amy Khor Lean Suan outlined several initia...
2,1,107,1_hdb_flats_flat_housing,"[hdb, flats, flat, housing, to, bto, the, for,...",[Ms Indranee Rajah emphasized the importance o...
3,2,72,2_questions_permission_question_requested,"[questions, permission, question, requested, m...","[Ms Gan Siow Huang, on behalf of the Minister ..."
4,3,69,3_employers_mom_employees_manpower,"[employers, mom, employees, manpower, work, fw...",[Flexible Work Arrangements (FWAs) are increas...
5,4,55,4_msf_social_family_and,"[msf, social, family, and, families, to, suppo...",[Mr Eric Chua thanked Members for their robust...
6,5,53,5_sports_arts_and_the,"[sports, arts, and, the, singapore, to, in, cu...",[Mr Eric Chua emphasized the importance of spo...
7,6,44,6_healthcare_moh_health_and,"[healthcare, moh, health, and, to, the, public...",[The National Electronic Health Record (NEHR) ...
8,7,43,7_students_moe_schools_learning,"[students, moe, schools, learning, education, ...",[Students with special educational needs (SEN)...
9,8,41,8_the_and_to_investment,"[the, and, to, investment, tax, for, financial...",[Mr Shawn Huang Wei Zhong addressed several po...
10,9,41,9_energy_climate_emissions_carbon,"[energy, climate, emissions, carbon, to, singa...","[Mr Teo Chee Hean, speaking as Chairman of the..."
11,10,40,10_religious_harmony_racial_the,"[religious, harmony, racial, the, that, of, an...",[Mr K Shanmugam moved the Second Reading of th...
12,11,39,11_ms_the_town_members,"[ms, the, town, members, rajah, indranee, of, ...",[Mr Heng Swee Keat moved a Motion in Parliamen...
13,12,39,12_fire_scdf_safety_saf,"[fire, scdf, safety, saf, and, to, the, of, de...","[Ms Sun Xueling, on behalf of the Minister for..."
14,13,37,13_trade_global_us_economic,"[trade, global, us, economic, and, singapore, ...",[Mr Chan Chun Sing outlined Singapore's econom...
15,14,36,14_ecda_preschool_early_childcare,"[ecda, preschool, early, childcare, preschools...",[Ms Sun Xueling addressed concerns raised by a...
16,15,36,15_graduates_skills_training_skillsfuture,"[graduates, skills, training, skillsfuture, em...",[Ms Gan Siow Huang outlined the progress and f...
17,16,35,16_nric_numbers_statement_ministerial,"[nric, numbers, statement, ministerial, teo, t...",[Mrs Josephine Teo announced that the Parliame...
18,17,34,17_medisave_patients_healthcare_medical,"[medisave, patients, healthcare, medical, dent...",[Mr Ong Ye Kung highlighted the significant in...
19,18,34,18_water_waste_recycling_nea,"[water, waste, recycling, nea, plastic, and, p...",[Dr Amy Khor Lean Suan thanked Members for the...
20,19,30,19_properties_land_ura_property,"[properties, land, ura, property, residential,...",[The occupancy cap for private residential pro...
21,20,29,20_online_media_imda_content,"[online, media, imda, content, the, to, and, g...",[Singapore's approach to online content regula...
22,21,28,21_workers_employment_career_older,"[workers, employment, career, older, job, and,...",[Mrs Josephine Teo highlighted that the median...
23,22,27,22_disabilities_persons_with_support,"[disabilities, persons, with, support, assista...","[The Government collaborates with the people, ..."
24,23,25,23_scams_scam_ro_police,"[scams, scam, ro, police, the, money, to, bank...","[Ms Sun Xueling, on behalf of the Minister for..."
25,24,24,24_food_sfa_safety_and,"[food, sfa, safety, and, to, the, local, fish,...",[Ms Grace Fu Hai Yien moved the Bill for a sec...
26,25,23,25_cdc_vouchers_heartland_households,"[cdc, vouchers, heartland, households, communi...","[Since January 2023, the Community Development..."
27,26,22,26_cpf_members_retirement_monies,"[cpf, members, retirement, monies, scheme, nom...",[Mrs Josephine Teo addressed several key issue...
28,27,21,27_nparks_pet_wildlife_animal,"[nparks, pet, wildlife, animal, parks, to, and...",[The National Parks Board (NParks) is undertak...
29,28,21,28_humanitarian_aid_singapore_assistance,"[humanitarian, aid, singapore, assistance, mfa...",[Dr Vivian Balakrishnan addressed the situatio...
30,29,21,29_ai_ip_and_the,"[ai, ip, and, the, enterprise, innovation, sin...",[Mr Tan Kiat How emphasized the importance of ...
31,30,20,30_nea_dengue_littering_surveillance,"[nea, dengue, littering, surveillance, mosquit...",[Dr Amy Khor Lean Suan addressed the issue of ...
32,31,18,31_hsa_vaping_health_sciences,"[hsa, vaping, health, sciences, authority, eva...",[The Health Sciences Authority (HSA) uses a ri...
33,32,17,32_students_universities_aus_scholarships,"[students, universities, aus, scholarships, in...",[Mr Ong Ye Kung addressed three questions rega...
34,33,13,33_presumptions_shanmugam_drugs_mda,"[presumptions, shanmugam, drugs, mda, the, cou...",[Mr Shanmugam seeks to suspend Standing Order ...
35,34,11,34_mothers_ltvp_surrogacy_visit,"[mothers, ltvp, surrogacy, visit, singaporean,...","[Currently, Assisted Reproduction Technology (..."
36,35,11,35_expenditure_estimates_supply_year,"[expenditure, estimates, supply, year, financi...",[Mr Chee Hong Tat reported that the Committee ...
37,36,10,36_bill_amendment_bills_reading,"[bill, amendment, bills, reading, moved, fai, ...","[Ms Sun Xueling, on behalf of the Minister for..."

In [5]:
merged_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2439,-1_the_and_to_of,"[the, and, to, of, for, in, that, is, with, on]",NaN
1,0,224,0_nos_requested_questions_permission,"[nos, requested, questions, permission, combin...",NaN
2,1,178,1_saf_defence_ns_mindef,"[saf, defence, ns, mindef, servicemen, ng, for...",NaN
3,2,150,2_smes_companies_innovation_industry,"[smes, companies, innovation, industry, produc...",NaN
4,3,164,3_mas_financial_moneylenders_bill,"[mas, financial, moneylenders, bill, regulator...",NaN
...,...,...,...,...,...
147,146,10,146_injuries_injury_reporting_nonreporting,"[injuries, injury, reporting, nonreporting, wo...",NaN
148,147,10,147_huat_png_eng_clarification,"[huat, png, eng, clarification, leon, perera, ...",NaN
149,148,10,148_comcare_assistance_smta_lowincome,"[comcare, assistance, smta, lowincome, social,...",NaN
150,149,35,149_nric_numbers_statement_ministerial,"[nric, numbers, statement, ministerial, teo, t...",NaN
151,150,10,150_bill_amendment_bills_reading,"[bill, amendment, bills, reading, moved, fai, ...",NaN

In [6]:
conn = sqlite3.connect("db/axiom.db")  # Creates or opens the database file
cursor = conn.cursor()

cursor.execute('''
    SELECT claim
    FROM claims c
''')

data = cursor.fetchall()
conn.close()

print(len(data))

64002

In [7]:
claims = []
for entry in data:
    claims.append(entry[0])

base = BERTopic()
topics, probs = base.fit_transform(claims[0:60000])


new = BERTopic()
topics, probs = new.fit_transform(claims[60000:64002])

merged_model = BERTopic.merge_models([base, new])

In [8]:
base.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,22888,-1_we_not_be_the,"[we, not, be, the, and, or, are, of, to, in]",[The Government will continue to extend outrea...
1,0,646,0_water_pub_johor_pubs,"[water, pub, johor, pubs, desalination, river,...",[PUB supports businesses implementing water-ef...
2,1,597,1_moh_healthcare_care_mohs,"[moh, healthcare, care, mohs, nursing, provide...",[MOH introduced new care standards for nursing...
3,2,453,2_moe_mks_schools_school,"[moe, mks, schools, school, students, learning...",[The Ministry of Education (MOE) provides addi...
4,3,446,3_mom_employers_manpower_moms,"[mom, employers, manpower, moms, workers, disc...",[MOM has not done any study into under-employm...
...,...,...,...,...,...
853,852,10,852_bail_accused_nonbailable_bond,"[bail, accused, nonbailable, bond, released, o...","[If assessed suitable for bail again, the Poli..."
854,853,10,853_ghg_emissions_525_greenhouse,"[ghg, emissions, 525, greenhouse, carbon, lulu...",[The LULUCF sector accounts for about 0.1% of ...
855,854,10,854_overcharging_devices_charging_batteries,"[overcharging, devices, charging, batteries, i...",[UL2272 compliant devices prevent overcharging...
856,855,10,855_vulnerable_taxes_transfers_kin,"[vulnerable, taxes, transfers, kin, volunteers...",[The increase in social spending in recent yea...
857,856,10,856_ejc_jc_eunoia_jcs,"[ejc, jc, eunoia, jcs, ip, pathway, communitya...",[MOE set up Eunoia Junior College (EJC) to cat...

In [9]:
new.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1313,-1_the_and_in_to,"[the, and, in, to, of, for, is, will, be, with]",[Together with other initiatives to promote in...
1,0,110,0_medishield_life_premiums_medisave,"[medishield, life, premiums, medisave, coverag...",[The Government will provide strong support in...
2,1,99,1_hdb_flat_flats_housing,"[hdb, flat, flats, housing, owners, mortgage, ...",[For low-income households who cannot afford a...
3,2,84,2_mental_autism_health_disability,"[mental, autism, health, disability, support, ...","[The Government closely partners the people, p..."
4,3,71,3_lta_inspection_cng_parking,"[lta, inspection, cng, parking, vehicles, pmds...",[LTA is working with taxi operators that have ...
...,...,...,...,...,...
99,98,11,98_cannabis_seized_kg_amount,"[cannabis, seized, kg, amount, drug, abused, i...","[In 2016, the amount of cannabis seized contin..."
100,99,10,99_breeding_mosquito_detected_nea,"[breeding, mosquito, detected, nea, dengue, ha...",[NEA will monitor the enhanced regime to ensur...
101,100,10,100_challenges_groups_cocreate_fosters,"[challenges, groups, cocreate, fosters, impact...","[Co-workers, colleagues at work, friends, and ..."
102,101,10,101_households_pc_access_neu,"[households, pc, access, neu, plus, programme,...",[The NEU PC Plus Programme provides a subsidis...
103,102,10,102_ea_act_salary_employment,"[ea, act, salary, employment, employees, affec...",[The EA will be amended to protect employees f...

In [10]:
merged_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,24201,-1_we_not_be_the,"[we, not, be, the, and, or, are, of, to, in]",NaN
1,0,677,0_water_pub_johor_pubs,"[water, pub, johor, pubs, desalination, river,...",NaN
2,1,649,1_moh_healthcare_care_mohs,"[moh, healthcare, care, mohs, nursing, provide...",NaN
3,2,516,2_moe_mks_schools_school,"[moe, mks, schools, school, students, learning...",NaN
4,3,446,3_mom_employers_manpower_moms,"[mom, employers, manpower, moms, workers, disc...",NaN
...,...,...,...,...,...
867,866,13,866_polytechnic_ann_ngee_brochez,"[polytechnic, ann, ngee, brochez, temasek, che...",NaN
868,867,13,867_mayflies_reservoir_water_around,"[mayflies, reservoir, water, around, insects, ...",NaN
869,868,11,868_heritage_engagement_nhb_sessions,"[heritage, engagement, nhb, sessions, plan, st...",NaN
870,869,11,869_disease_kawasaki_dr_chia,"[disease, kawasaki, dr, chia, paediatrician, t...",NaN
871,870,10,870_ea_act_salary_employment,"[ea, act, salary, employment, employees, affec...",NaN

In [11]:
conn = sqlite3.connect("db/axiom.db")  # Creates or opens the database file
cursor = conn.cursor()

cursor.execute('''
    SELECT content, summary
    FROM sections s
    ORDER BY date
''')

data = cursor.fetchall()
conn.close()

print(len(data))

6448

In [ ]:
content = []
summary = []
for entry in data:
    content.append(entry[0])
    summary.append(entry[1])

base = BERTopic()
topics, probs = base.fit_transform(summary[0:6000])


new = BERTopic()
topics, probs = new.fit_transform(summary[6000:6448])

merged_model = BERTopic.merge_models([base, new])

In [ ]:
base.get_topic_info()

In [ ]:
new.get_topic_info()

In [ ]:
merged_model.get_topic_info()