In [1]:
import sqlite3

import pandas as pd
from bertopic import BERTopic

conn = sqlite3.connect("../db/axiom.db")  # Creates or opens the database file
cursor = conn.cursor()

cursor.execute('''
    SELECT speech, summary
    FROM speeches s
    ORDER BY date
''')

data = cursor.fetchall()
conn.close()

print(len(data))

/home/tytan216/volume/tzeyoung/Policy_RLHF/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

8951

In [2]:
speeches = []
summary = []
for entry in data:
    speeches.append(entry[0])
    summary.append(entry[1])

base = BERTopic()
base_topics, base_probs = base.fit_transform(summary[0:7000])

new = BERTopic()
new_topics, new_probs = new.fit_transform(summary[7000:8975])

merged_model = BERTopic.merge_models([base, new])

In [3]:
df = base.get_topic_info()
df

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1900,-1_the_and_to_of,"[the, and, to, of, for, in, that, with, on, is]",[Mr Lawrence Wong addressed several key aspect...
1,0,314,0_economic_trade_singapore_smes,"[economic, trade, singapore, smes, growth, com...",[Mr Lim Hng Kiang presented a detailed analysi...
2,1,111,1_combine_nos_requested_questions,"[combine, nos, requested, questions, permissio...",[Mr Lawrence Wong requested to combine Questio...
3,2,102,2_hdb_housing_rental_flat,"[hdb, housing, rental, flat, flats, households...",[Ms Sun Xueling discussed the case of Mdm Narz...
4,3,102,3_saf_ns_defence_servicemen,"[saf, ns, defence, servicemen, ng, mindef, tra...",[Dr Ng Eng Hen emphasized the importance of ma...
...,...,...,...,...,...
149,148,11,148_wis_workers_workfare_income,"[wis, workers, workfare, income, lowwage, perc...",[Mrs Josephine Teo presented data on the Workf...
150,149,11,149_silver_payouts_support_scheme,"[silver, payouts, support, scheme, elderly, bo...",[The Silver Support Scheme targets the bottom ...
151,150,11,150_bca_building_structural_steel,"[bca, building, structural, steel, windows, ow...",[Owners of landed properties need their neighb...
152,151,11,151_officers_reemployed_apos_retiring,"[officers, reemployed, apos, retiring, team, h...",[The Home Team operates in a dynamic environme...
153,152,11,152_sexual_abuse_sexuality_police,"[sexual, abuse, sexuality, police, child, self...",[Keeping children safe from sexual abuse is a ...

In [4]:
new.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,465,-1_the_and_of_to,"[the, and, of, to, in, for, that, with, is, on]",[Mr Edwin Tong Chun Fai thanked the Members wh...
1,0,197,0_employers_workers_employment_the,"[employers, workers, employment, the, mom, and...","[Mr Zaqy Mohamad, on behalf of the Minister fo..."
2,1,195,1_transport_bus_lta_the,"[transport, bus, lta, the, to, road, safety, a...",[Mr Chee Hong Tat addressed several key points...
3,2,111,2_hdb_flats_housing_flat,"[hdb, flats, housing, flat, bto, to, rental, f...",[Mr Desmond Lee outlined several key initiativ...
4,3,61,3_family_families_social_msf,"[family, families, social, msf, and, child, ch...",[Mr Desmond Lee provided an overview of the pr...
5,4,57,4_permission_questions_requested_combine,"[permission, questions, requested, combine, no...","[Ms Gan Siow Huang, on behalf of the Minister ..."
6,5,49,5_energy_climate_emissions_carbon,"[energy, climate, emissions, carbon, singapore...","[Mr Teo Chee Hean, speaking as Chairman of the..."
7,6,49,6_tax_the_and_to,"[tax, the, and, to, consumer, for, gst, of, in...",[Mr Lawrence Wong moved the motion to approve ...
8,7,45,7_religious_harmony_the_racial,"[religious, harmony, the, racial, that, of, co...",[Ms Sun Xueling outlined three key proposals i...
9,8,43,8_global_trade_us_singapore,"[global, trade, us, singapore, economic, and, ...",[Mr Chan Chun Sing outlined the state of Singa...
10,9,35,9_waste_water_recycling_nea,"[waste, water, recycling, nea, plastic, packag...",[Dr Amy Khor Lean Suan thanked Members for the...
11,10,35,10_students_schools_moe_school,"[students, schools, moe, school, education, pr...",[Students with special educational needs (SEN)...
12,11,33,11_ecda_preschool_childcare_early,"[ecda, preschool, childcare, early, childhood,...",[The early childhood educator workforce in Sin...
13,12,32,12_disabilities_persons_with_support,"[disabilities, persons, with, support, employm...",[The government supports adults with disabilit...
14,13,31,13_properties_land_ura_residential,"[properties, land, ura, residential, redevelop...",[Mr Keith Chua asked the Minister about the pr...
15,14,29,14_moh_diseases_cda_health,"[moh, diseases, cda, health, disease, and, inf...","[In the last three years, Singapore experience..."
16,15,25,15_speech_time_indranee_ms,"[speech, time, indranee, ms, rajah, present, a...",[Mr Zaqy Mohamad requested the Speaker's conse...
17,16,25,16_food_sfa_safety_and,"[food, sfa, safety, and, local, the, bill, bus...",[Dr Koh Poh Koon addressed several key themes ...
18,17,23,17_nric_numbers_teo_the,"[nric, numbers, teo, the, acra, josephine, biz...",[Mrs Josephine Teo addressed several points ra...
19,18,22,18_students_universities_aus_scholarships,"[students, universities, aus, scholarships, in...",[Mr Ong Ye Kung addressed three questions rega...
20,19,22,19_medisave_patients_medical_outpatient,"[medisave, patients, medical, outpatient, heal...","[The Government's healthcare framework, includ..."
21,20,22,20_scams_scam_police_ro,"[scams, scam, police, ro, money, gambling, to,...","[Ms Sun Xueling, on behalf of the Minister for..."
22,21,22,21_cdc_vouchers_heartland_households,"[cdc, vouchers, heartland, households, scheme,...","[Since January 2023, the Community Development..."
23,22,21,22_mothers_art_ltvp_ar,"[mothers, art, ltvp, ar, women, couples, singa...",[For women unable to conceive due to egg quali...
24,23,21,23_cpf_retirement_members_monies,"[cpf, retirement, members, monies, savings, sc...",[Mrs Josephine Teo addressed several key issue...
25,24,21,24_ai_enterprise_and_digital,"[ai, enterprise, and, digital, smes, ip, enter...",[Ms Tin Pei Ling emphasized the importance of ...
26,25,20,25_hsa_health_sciences_authority,"[hsa, health, sciences, authority, drugs, drug...",[The Health Sciences Authority (HSA) evaluates...
27,26,19,26_nparks_pet_animal_parks,"[nparks, pet, animal, parks, dog, dogs, welfar...","[In 2018, the National Parks Board (NParks) in..."
28,27,18,27_nea_dengue_mosquito_littering,"[nea, dengue, mosquito, littering, breeding, s...",[The National Environment Agency (NEA) employs...
29,28,17,28_humanitarian_aid_gaza_singapore,"[humanitarian, aid, gaza, singapore, mfa, assi...",[Dr Vivian Balakrishnan addressed the situatio...
30,29,16,29_sports_sportsg_sport_athletes,"[sports, sportsg, sport, athletes, facilities,...","[The Singapore Sports School, a specialised in..."
31,30,15,30_school_bullying_schools_students,"[school, bullying, schools, students, student,...","[MOE takes a serious view of bullying, ensurin..."
32,31,15,31_arts_nac_culture_mccy,"[arts, nac, culture, mccy, artists, busking, d...",[Mr Darryl David highlighted that Singapore su...
33,32,14,32_ns_saf_nsmen_servicemen,"[ns, saf, nsmen, servicemen, training, scdf, d...",[The structure for a career within the Singapo...
34,33,13,33_digital_seniors_government_access,"[digital, seniors, government, access, househo...",[Singapore's Smart Nation strategy prioritizes...
35,34,12,34_stalls_hawker_hawkers_food,"[stalls, hawker, hawkers, food, nea, stallhold...",[Under the Environmental Public Health (Food H...
36,35,12,35_fire_scdf_safety_buildings,"[fire, scdf, safety, buildings, fires, aeds, w...","[Ms Sun Xueling, on behalf of the Minister for..."
37,36,12,36_healthcare_moh_telemedicine_health,"[healthcare, moh, telemedicine, health, medica...",[The National Electronic Health Record (NEHR) ...
38,37,12,37_htx_security_data_cyber,"[htx, security, data, cyber, cybersecurity, te...",[Dr Janil Puthucheary emphasized the importanc...
39,38,12,38_nurses_nursing_healthcare_care,"[nurses, nursing, healthcare, care, average, y...",[Mr Ong Ye Kung stated that nurses in Singapor...
40,39,11,39_singpass_ica_ecoa_individuals,"[singpass, ica, ecoa, individuals, addresses, ...",[Mrs Josephine Teo addressed questions raised ...
41,40,11,40_expenditure_estimates_supply_year,"[expenditure, estimates, supply, year, financi...",[Mr Zaqy Mohamad reported that the Committee o...
42,41,11,41_zaqy_mohamad_reconvene_session,"[zaqy, mohamad, reconvene, session, chairmans,...",[Mr Zaqy Mohamad requested the Chairman's cons...
43,42,10,42_online_media_content_harmful,"[online, media, content, harmful, safety, soci...",[The Government aims to protect vulnerable use...
44,43,10,43_bill_moved_amendment_bills,"[bill, moved, amendment, bills, debate, judges...","[Mr Edwin Tong Chun Fai, on behalf of the Mini..."

In [5]:
merged_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2387,-1_the_and_to_of,"[the, and, to, of, for, in, that, with, on, is]",NaN
1,0,378,0_economic_trade_singapore_smes,"[economic, trade, singapore, smes, growth, com...",NaN
2,1,168,1_combine_nos_requested_questions,"[combine, nos, requested, questions, permissio...",NaN
3,2,213,2_hdb_housing_rental_flat,"[hdb, housing, rental, flat, flats, households...",NaN
4,3,116,3_saf_ns_defence_servicemen,"[saf, ns, defence, servicemen, ng, mindef, tra...",NaN
...,...,...,...,...,...
154,153,23,153_nric_numbers_teo_the,"[nric, numbers, teo, the, acra, josephine, biz...",NaN
155,154,11,154_singpass_ica_ecoa_individuals,"[singpass, ica, ecoa, individuals, addresses, ...",NaN
156,155,11,155_zaqy_mohamad_reconvene_session,"[zaqy, mohamad, reconvene, session, chairmans,...",NaN
157,156,10,156_online_media_content_harmful,"[online, media, content, harmful, safety, soci...",NaN
158,157,10,157_bill_moved_amendment_bills,"[bill, moved, amendment, bills, debate, judges...",NaN

In [6]:
conn = sqlite3.connect("../db/axiom.db")  # Creates or opens the database file
cursor = conn.cursor()

cursor.execute('''
    SELECT claim
    FROM claims c
''')

data = cursor.fetchall()
conn.close()

print(len(data))

66640

In [7]:
claims = []
for entry in data:
    claims.append(entry[0])

base = BERTopic()
topics, probs = base.fit_transform(claims[0:60000])


new = BERTopic()
topics, probs = new.fit_transform(claims[60000:64002])

merged_model = BERTopic.merge_models([base, new])

In [8]:
base.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,22299,-1_not_the_be_government,"[not, the, be, government, of, are, to, for, i...",[More than 7.5 million commuters use the bus o...
1,0,715,0_moh_healthcare_care_mohs,"[moh, healthcare, care, mohs, nursing, provide...",[MSF and MOH will continue to work together to...
2,1,713,1_students_teachers_school_schools,"[students, teachers, school, schools, learning...",[Students learn that everyone has the right to...
3,2,680,2_water_pub_johor_desalination,"[water, pub, johor, desalination, river, pubs,...",[PUB has stringent security measures to ensure...
4,3,465,3_mom_employers_manpower_workers,"[mom, employers, manpower, workers, foreign, m...",[MOM will continue to take in feedback to revi...
...,...,...,...,...,...
783,782,10,782_overweight_obesity_adulthood_hypertension,"[overweight, obesity, adulthood, hypertension,...",[Overweight children at the upper end of the c...
784,783,10,783_posting_difference_cutoff_nonaffiliates,"[posting, difference, cutoff, nonaffiliates, a...",[The median difference in cut-off points mirro...
785,784,10,784_rain_punggol_coney_rustic,"[rain, punggol, coney, rustic, carriageway, fl...",[These rain shelters are located under flyover...
786,785,10,785_broadcasts_parliamentary_footages_parliament,"[broadcasts, parliamentary, footages, parliame...",[MCI has multiple convenient channels for the ...
787,786,10,786_wholeofnation_deliver_service_better,"[wholeofnation, deliver, service, better, mult...",[These changes allow the Public Service to dev...

In [9]:
new.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1617,-1_the_to_and_of,"[the, to, and, of, in, we, are, this, for, have]",[We are training public officers in data analy...
1,0,160,0_students_schools_education_school,"[students, schools, education, school, learnin...","[Today, about 30,000 SEN students, or four in ..."
2,1,134,1_not_do_data_we,"[not, do, data, we, track, no, have, any, plan...",[We do not track the age group of the employee...
3,2,107,2_bus_commuters_rail_mrt,"[bus, commuters, rail, mrt, trainkm, transport...",[Under the Bus Service Enhancement Programme (...
4,3,73,3_healthcare_care_patients_medical,"[healthcare, care, patients, medical, clinics,...",[We increased subsidies at outpatient clinics ...
...,...,...,...,...,...
74,73,12,73_scholarships_nus_awarded_mendaki,"[scholarships, nus, awarded, mendaki, psc, ntu...","[Today, all individuals awarded PSC scholarshi..."
75,74,11,74_trees_inspected_pruned_tree,"[trees, inspected, pruned, tree, nparks, pruni...",[Trees under NParks' purview are regularly ins...
76,75,11,75_offence_imprisonment_20000_fine,"[offence, imprisonment, 20000, fine, punishabl...","[Under the Employment of Foreign Manpower Act,..."
77,76,10,76_tv_mediacorp_viewing_dtv,"[tv, mediacorp, viewing, dtv, media, preparedn...",[This funding supported the development of cap...
78,77,10,77_servicemen_mental_voyage_commanders,"[servicemen, mental, voyage, commanders, healt...","[To engender commitment, we must train Nationa..."

In [10]:
merged_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,23916,-1_not_the_be_government,"[not, the, be, government, of, are, to, for, i...",NaN
1,0,715,0_moh_healthcare_care_mohs,"[moh, healthcare, care, mohs, nursing, provide...",NaN
2,1,873,1_students_teachers_school_schools,"[students, teachers, school, schools, learning...",NaN
3,2,747,2_water_pub_johor_desalination,"[water, pub, johor, desalination, river, pubs,...",NaN
4,3,465,3_mom_employers_manpower_workers,"[mom, employers, manpower, workers, foreign, m...",NaN
...,...,...,...,...,...
788,787,32,787_parks_hectares_nature_land,"[parks, hectares, nature, land, reserves, park...",NaN
789,788,14,788_leave_employee_sick_doctor,"[leave, employee, sick, doctor, paid, days, me...",NaN
790,789,12,789_scholarships_nus_awarded_mendaki,"[scholarships, nus, awarded, mendaki, psc, ntu...",NaN
791,790,11,790_trees_inspected_pruned_tree,"[trees, inspected, pruned, tree, nparks, pruni...",NaN
792,791,10,791_tv_mediacorp_viewing_dtv,"[tv, mediacorp, viewing, dtv, media, preparedn...",NaN

In [11]:
conn = sqlite3.connect("../db/axiom.db")  # Creates or opens the database file
cursor = conn.cursor()

cursor.execute('''
    SELECT content, summary
    FROM sections s
    ORDER BY date
''')

data = cursor.fetchall()
conn.close()

print(len(data))

6439

In [12]:
content = []
summary = []
for entry in data:
    content.append(entry[0])
    summary.append(entry[1])

base = BERTopic()
topics, probs = base.fit_transform(summary[0:6000])


new = BERTopic()
topics, probs = new.fit_transform(summary[6000:6448])

merged_model = BERTopic.merge_models([base, new])

In [13]:
base.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1666,-1_the_and_of_to,"[the, and, of, to, for, in, that, mr, with, is]",[The debate centered on the theme of value-for...
1,0,269,0_flats_hdb_flat_housing,"[flats, hdb, flat, housing, bto, rental, appli...",[Dr Intan Azura Mokhtar inquired about the num...
2,1,153,1_read_time_bill_presented,"[read, time, bill, presented, printed, second,...",[The Income Tax Act (Chapter 134 of the 2014 R...
3,2,144,2_trade_smes_companies_industry,"[trade, smes, companies, industry, economic, s...",[The Minister for Trade and Industry (Trade) a...
4,3,132,3_mas_financial_banks_credit,"[mas, financial, banks, credit, payment, regul...",[The Minister for Education (Higher Education ...
...,...,...,...,...,...
141,140,10,140_eip_hdb_flats_ethnic,"[eip, hdb, flats, ethnic, flat, sell, subletti...",[Ms Rahayu Mahzam asked the Minister for Natio...
142,141,10,141_family_justice_applications_maintenance,"[family, justice, applications, maintenance, c...",[Ms Rahayu Mahzam asked the Minister for Socia...
143,142,10,142_surrogacy_marriages_marriage_old,"[surrogacy, marriages, marriage, old, birth, b...",[Ms Anthea Ong and Mr Mohamed Irshad asked the...
144,143,10,143_internships_ecg_ite_graduates,"[internships, ecg, ite, graduates, students, i...",[Ms Rahayu Mahzam asked the Minister for Educa...
145,144,10,144_fdws_eas_employers_ea,"[fdws, eas, employers, ea, domestic, mom, refu...",[Ms Sylvia Lim inquired about the options avai...

In [14]:
new.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,343,0_the_and_to_of,"[the, and, to, of, for, in, with, that, mr, on]",[Mr Melvin Yong Yik Chye (Radin Mas) emphasize...
1,1,51,1_the_and_to_for,"[the, and, to, for, hdb, of, in, mr, flats, ho...",[Miss Cheryl Chan Wei Ling (East Coast) highli...
2,2,45,2_the_of_to_for,"[the, of, to, for, estimates, expenditure, com...","[The Minister of State for Home Affairs, Assoc..."

In [15]:
merged_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2009,-1_the_and_of_to,"[the, and, of, to, for, in, that, mr, with, is]",NaN
1,0,320,0_flats_hdb_flat_housing,"[flats, hdb, flat, housing, bto, rental, appli...",NaN
2,1,153,1_read_time_bill_presented,"[read, time, bill, presented, printed, second,...",NaN
3,2,144,2_trade_smes_companies_industry,"[trade, smes, companies, industry, economic, s...",NaN
4,3,132,3_mas_financial_banks_credit,"[mas, financial, banks, credit, payment, regul...",NaN
...,...,...,...,...,...
141,140,10,140_eip_hdb_flats_ethnic,"[eip, hdb, flats, ethnic, flat, sell, subletti...",NaN
142,141,10,141_family_justice_applications_maintenance,"[family, justice, applications, maintenance, c...",NaN
143,142,10,142_surrogacy_marriages_marriage_old,"[surrogacy, marriages, marriage, old, birth, b...",NaN
144,143,10,143_internships_ecg_ite_graduates,"[internships, ecg, ite, graduates, students, i...",NaN
145,144,10,144_fdws_eas_employers_ea,"[fdws, eas, employers, ea, domestic, mom, refu...",NaN